In [1]:
import pandas as pd

In [4]:
df=pd.read_excel("house-pre.xlsx") # if excel will not be opened # !pip install openpyxl

In [5]:
df

     Area (sq ft)  Bedrooms  Bathrooms  Age (years)  Location Score  Price ($)
0            1360         2          2           13             2.1     433957
1            4272         3          4           26             1.2     866023
2            3592         1          1           40             7.9     691837
3             966         6          3           39             8.3     712165
4            4926         1          3           27             2.1     921202
..            ...       ...        ...          ...             ...        ...
995          3261         4          1           46             7.0     785330
996          3179         2          3           16             9.4     917865
997          2606         1          2           39             3.4     531024
998          4723         5          4           27             6.5    1127981
999          3268         1          4           11             7.1     824312

[1000 rows x 6 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Area (sq ft)    1000 non-null   int64
 1   Bedrooms        1000 non-null   int64
 2   Bathrooms       1000 non-null   int64
 3   Age (years)     1000 non-null   int64
 4   Location Score  1000 non-null   float64
 5   Price ($)       1000 non-null   int64
dtypes: float64(1), int64(5)
memory usage: 47.0 KB

In [7]:
df.shape

(1000, 6)

In [8]:
df.describe()

,Area (sq ft),Bedrooms,Bathrooms,Age (years),Location Score,Price ($)
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03
mean,2815.422000,3.457000,2.507000,25.408000,5.470400,7.550107e+05
std,1255.514921,1.709114,1.134565,14.640146,2.602702,2.258313e+05
min,503.000000,1.000000,1.000000,0.000000,1.000000,1.266690e+05
25%,1749.500000,2.000000,1.750000,13.000000,3.200000,5.772892e+05
50%,2862.500000,3.000000,2.000000,26.000000,5.500000,7.612465e+05
75%,3849.500000,5.000000,4.000000,38.000000,7.725000,9.142230e+05
max,4999.000000,6.000000,4.000000,50.000000,10.000000,1.336871e+06

In [10]:
df.isnull().sum()

Area (sq ft)      0
Bedrooms          0
Bathrooms         0
Age (years)       0
Location Score    0
Price ($)         0
dtype: int64

In [12]:
x=df.drop("Price ($)",axis=1)
y=df["Price ($)"]

In [13]:
x

     Area (sq ft)  Bedrooms  Bathrooms  Age (years)  Location Score
0            1360         2          2           13             2.1
1            4272         3          4           26             1.2
2            3592         1          1           40             7.9
3             966         6          3           39             8.3
4            4926         1          3           27             2.1
..            ...       ...        ...          ...             ...
995          3261         4          1           46             7.0
996          3179         2          3           16             9.4
997          2606         1          2           39             3.4
998          4723         5          4           27             6.5
999          3268         1          4           11             7.1

[1000 rows x 5 columns]

In [14]:
y

0       433957
1       866023
2       691837
3       712165
4       921202
        ...
995     785330
996     917865
997     531024
998    1127981
999     824312
Name: Price ($), Length: 1000, dtype: int64

In [16]:
type(x) # To check type

pandas.core.frame.DataFrame

In [17]:
type(y) # To check type

pandas.core.series.Series

In [18]:
from sklearn.model_selection import train_test_split

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [32]:
x_train

     Area (sq ft)  Bedrooms  Bathrooms  Age (years)  Location Score
647          1023         5          1           25             3.2
695          4507         4          4           15             8.6
73           2562         3          2           11             4.9
13           1684         4          1           41             3.7
561          4969         1          1            3             1.2
..            ...       ...        ...          ...             ...
119          1863         5          1           27             3.1
148          1198         2          1           15             6.9
493          4022         6          2           47             5.6
918          4201         5          4           40             7.1
758           820         5          1           44             3.5

[800 rows x 5 columns]

In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
reg=LinearRegression()

In [35]:
reg.fit(x_train,y_train)

LinearRegression()

In [36]:
import pickle

In [37]:
pickle.dump(reg,open("house_pred.pkl","wb"))